Рендер компонента главной страницы
htmlacademy-react/1814373-what-to-watch-7 pull request #4
Opened 2021-06-03 12:47 UTC by MiKeBronko

### Рендер главной страницы

1. Добавлен компонент карточки превью фильма `/src/components/film-card/film-card.jsx`
2. Добавлен компонент главной страницы  `/src/components/main-screen/main-screen.jsx`
3. Добавлен рендер главной страницы `/src/components/app/app.jsx`
4. Добавлен рендер компонента APP  `src/index.jsx`
5. Проверка Eslint работает по команде 
> `npm run eslint`
Есть предупреждение, не знаю пока как решить.
_project/src/components/main-screen/main-screen.jsx
  109:44  warning  Unexpected use of comma operator  no-sequences_

2021-06-03 15:37 UTC, ekazakov requested changes

2021-06-03 15:37 UTC, ekazakov commented on project/src/index.js
> +const dateReleasePromoFilm = '2014';
Можно все эти переменные объединить в один объект — `promoFilm` и дальше одним пропсом передавать в `App` и `MainScreen`

2021-06-03 15:37 UTC, ekazakov commented on project/src/index.js
> +  },
Посмотри описание структуры данных Film в https://up.htmlacademy.ru/react/7/project/what-to-watch. Советую поля которые там есть сразу добавить в моки. 
Если хочешь, можешь написать генерацию моков как в JS2

2021-06-03 15:37 UTC, ekazakov commented on project/src/components/main-screen/main-screen.jsx
> +                <FilmCardPreview key={image, name} image={image} name ={name}/>)
`key={image, name}` так не надо делать, тут не будет комбинированного ключа, в качестве ключа будет использоваться только `name`. Собственно это и причина ворнинга. 

Лучше так сделать:

```
elFilmCardPreview.map((film) =>
                <FilmCardPreview key={film.id} film={film} />)
```                

- Св-во `id` надо добавить в фильм(см коммент по мокам)
- Фильм передавать в `FilmCardPreview` одним пропсом

2021-06-04 00:16 UTC, MiKeBronko commented on project/src/index.js
> +  },
не был на курсе JS2. Не знаком с генерациией моков.

2021-06-04 00:18 UTC, MiKeBronko commented on project/src/components/main-screen/main-screen.jsx
> +                <FilmCardPreview key={image, name} image={image} name ={name}/>)
Фильм передавать в FilmCardPreview одним пропсом.
Безуспешно, приложении генерит ошибку, страницы не рендерится

2021-06-04 00:20 UTC, MiKeBronko commented on project/src/index.js
> +const dateReleasePromoFilm = '2014';
сделал

2021-06-06 22:42 UTC, merged