Module3 task1
htmlacademy-react/1814373-what-to-watch-7 pull request #6
Opened 2021-06-27 20:50 UTC by MiKeBronko

### Обратная сторона реальности

1. Добален компонет «Список фильмов». В стейте компонента  активная карточка с фильмом.
2. Добален компонет «Форма отправки комментария». Сохранение введённых в форму данных в state компонента
3. Новая директория _mocks_ с файлами film.js, review.js
4. Kлик по заголовку карточки с фильмом перенаправляет пользователя на страницу «Film» с подробным описанием фильма
5. Добавлен _pages_ содержащий страницы приложения.
6. Добавлен _elements_ содержащий карточку фильма и логотип сайта.
7. Хуки добавлены в директорию _hooks_

2021-06-28 13:22 UTC, ekazakov requested changes

2021-06-28 13:22 UTC, ekazakov commented on project/src/components/app/app.jsx
> +  films: PropTypes.array.isRequired,
Тут лучше `PropTypes.arrayOf(filmPropTypes)`, а `promoFilm` для просто `filmPropTypes`

2021-06-28 13:22 UTC, ekazakov commented on project/src/components/elements/film-card/film-card.prop.jsx
> +const filmPropTypes = {
Лучше сделать именованный экспорт:

```
export const filmPropTypes = {...}

export const filmCardPropTypes = {...}
```

2021-06-28 13:22 UTC, ekazakov commented on project/src/hooks/form-review/form-review.jsx
> +function FormReview () {
![image](https://user-images.githubusercontent.com/2683752/123641835-f8d30a00-d822-11eb-8b50-17f5b5f900a5.png)

Форма комментария это часть страницы фильма, т.е. это д.б. компонент, который рендерится внутри `FilmScreen`. 

1. Содержимое влкадок Overview/Details/Reviews будет отдельными компонентами
2. В компненте FilmScreen нужно завести стейт `activeTab` — которое будет принимать одно из 3 значений: overview(по умолчанию), details, review.
3. В зависимости от текущего значения `activeTab` надо ренедрить нужный компонент, например так

```
let tabContent = <Overview />

if ( activeTab === 'details') {
  tabContent = <Details />
}

return <div>
  {tabContent}
</div>
```

4. По клику на название вкладки значение `activeTab` будет меняться

2021-06-28 13:22 UTC, ekazakov commented on project/src/components/elements/film-card/film-card.jsx
> +        <Link className="small-film-card__link" to={`films/:${id}`}>{name}
Тут надо без `:` — `to={`films/${id}`}`. `:` нужно только в роутах(<Route/>)

2021-07-05 20:28 UTC, MiKeBronko commented on project/src/components/app/app.jsx
> +  films: PropTypes.array.isRequired,
App.propTypes = {
  >>>>>>>promoFilm: PropTypes.object., 

- для promoFilm не понял логику

  films: PropTypes.arrayOf(filmPropTypes),
  review: PropTypes.array.isRequired,
};

2021-07-05 20:35 UTC, MiKeBronko commented on project/src/components/elements/film-card/film-card.jsx
> +        <Link className="small-film-card__link" to={`films/:${id}`}>{name}
исправил

2021-07-05 20:38 UTC, MiKeBronko commented on project/src/hooks/form-review/form-review.jsx
> +function FormReview () {
_Создайте новый компонент «Форма отправки комментария». Разметку для компонента вы найдёте в файле add-review.html. Реализуйте сохранение введённых в форму данных в state компонента._

- Как то в задании нет намека на страницу с детальной информацией по фильму и вкладок/
- Форма для страницы review-screen.
<img width="1326" alt="Снимок экрана 2021-07-05 в 23 19 36" src="https://user-images.githubusercontent.com/48468888/124515442-2520f480-dde8-11eb-8886-8a51f1ce8932.png">
.

2021-07-05 20:38 UTC, MiKeBronko commented on project/src/components/elements/film-card/film-card.prop.jsx
> +const filmPropTypes = {
линт не собирает проект без export default
<img width="414" alt="Снимок экрана 2021-07-05 в 23 29 59" src="https://user-images.githubusercontent.com/48468888/124515780-f35c5d80-dde8-11eb-903e-4db8e40ee79b.png">

2021-07-05 20:38 UTC, MiKeBronko commented on project/src/components/elements/film-card/film-card.jsx
> +        <Link className="small-film-card__link" to={`films/:${id}`}>{name}
пофиксил

2021-07-06 08:25 UTC, ekazakov commented on project/src/components/app/app.jsx
> +  films: PropTypes.array.isRequired,
> для promoFilm не понял логику

Сори, не четко сформулировал. Я имел ввиду, что надо `promoFilm: PropTypes.shape(filmPropTypes).isRequired,`. Т.к. `promoFilm` — это тоже будет объект с данными фильма.

2021-07-06 08:26 UTC, ekazakov commented on project/src/components/elements/film-card/film-card.prop.jsx
> +const filmPropTypes = {
Ок, если так.

2021-07-06 08:46 UTC, ekazakov commented on project/src/hooks/form-review/form-review.jsx
> +function FormReview () {
Это я тоже напутал, извини :) Просто я заметил, что вкладки еще не сделаны и перепутал их с формой ревью

2021-07-06 08:48 UTC, merged